version: "3.8"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: videoplayer
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  
    ports:
      - "5432:5432"

  backend:
    build: ./video-player-backend
    container_name: video-player-backend
    restart: always
    depends_on:
      - postgres-db
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: videoplayer
      JWT_SECRET: b7ef4573ca24c626950c1023163cf3433e0fb260b7c70dc896327495d0dbdaba
    ports:
      - "5000:5000"

  frontend:
    build: ./video-player-frontend
    container_name: video-player-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
