version: "3.8"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: videoplayer
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./video-player-backend
    container_name: video-player-backend
    restart: always
    depends_on:
      - postgres-db
    environment:
      DB_NAME: videoplayer
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres-db
      JWT_SECRET: b7ef4573ca24c626950c1023163cf3433e0fb260b7c70dc896327495d0dbdaba
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./video-player-backend:/app
      - /app/node_modules

  frontend:
    build: ./video-player-frontend
    container_name: video-player-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      VITE_BACKEND_URL: "http://video-player-backend:5000"
    volumes:
      - ./video-player-frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
