version: "3.8"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./video-player-backend
    container_name: video-player-backend
    restart: always
    depends_on:
      - postgres-db
    env_file:
      - ./video-player-backend/.env  # 🔴 Carga el archivo .env en el backend
    environment:
      DOCKER_ENV: "true"  # 🔴 Variable para detectar si está en Docker
    ports:
      - "5000:5000"

  frontend:
    build: ./video-player-frontend
    container_name: video-player-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
