version: "3.8"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: videoplayer
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  
  backend:
    build: ./video-player-backend
    container_name: video-player-backend
    restart: always
    depends_on:
      postgres-db:
        condition: service_healthy 
    environment:
      DATABASE_URL: "postgres://postgres:password@postgres-db:5432/videoplayer"
    ports:
      - "5000:5000"
    healthcheck: 
      test: ["CMD", "pg_isready", "-h", "postgres-db", "-p", "5432", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s

  frontend:
    build: ./video-player-frontend
    container_name: video-player-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
